# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0019_auto_20160311_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='experiment_equation',
            field=models.TextField(blank=True),
        ),
    ]
